### ISSUE TITLE
[FEATURE] - One-World Border vs. Multi-World Border Toggle

### ISSUE THREAD

**Issue by sh0ckR6** [sh0ckR6/AchievementBorder#17]
### Is there an existing issue for this?

- [X] I have searched for this feature in the existing issues

## Overview
This would add a configuration setting that would allow the user to toggle which worlds the Border Control System affects

##### config.yml
```yaml
border-worlds:
  - overworld: true     # If true, the Border Control System will affect the overworld
  - nether: false       # If true, the Border Control System will affect the nether
  - end: true           # If true, the Border Control System will affect the end
```

### Other Solutions

There's not really any other options, the closest thing is to not let the player control this and have it hardcoded
